# Generated by Django 4.2.2 on 2023-06-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Student'), (1, 'Staff')], default=0, null=True),
        ),
    ]
