# Generated by Django 3.2.19 on 2023-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance_from_college', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bus_stop',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('bus_stops', models.ManyToManyField(to='buspass.BusStop')),
            ],
            options={
                'db_table': 'bus',
            },
        ),
    ]
