# Generated by Django 3.2.19 on 2023-06-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destination', to='buspass.busstop'),
        ),
    ]
