# Generated by Django 3.2.19 on 2023-06-15 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buspass', '0002_alter_bus_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBusPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('expire_at', models.DateField()),
                ('status', models.BooleanField()),
                ('boarding_point', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='buspass.busstop')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='buspass.bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_bus_pass',
            },
        ),
    ]
