# Generated by Django 3.2.19 on 2023-06-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0003_userbuspass'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuspass',
            name='fare',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
