# Generated by Django 3.2.19 on 2023-06-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buspass', '0005_rename_status_userbuspass_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
