# Generated by Django 3.2.19 on 2023-06-16 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buspass', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
